import { Controller } from "@nestjs/common";
import { GrpcMethod } from "@nestjs/microservices";
import { UsersService } from "./users.service";
import { ReadingPreferencesService } from "../reading-preferences/reading-preferences.service";
import { BookmarksService } from "../bookmarks/bookmarks.service";
import { BookmarkSyncService } from "../bookmarks/bookmark-sync.service";
import { AnnotationsService } from "../annotations/annotations.service";
import { AnnotationExportService } from "../annotations/annotation-export.service";
import { AnnotationUnificationService } from "../annotations/annotation-unification.service";
import { AnnotationRevisitationService } from "../annotations/annotation-revisitation.service";
import { AnnotationAiSummaryService } from "../annotations/annotation-ai-summary.service";
import { AnnotationSyncService } from "../annotations/annotation-sync.service";
import { LibraryService } from "../library/library.service";
import { LibrarySyncService } from "../library/library-sync.service";
import { LibraryDownloadService } from "../library/library-download.service";
import { LibraryStorageService } from "../library/library-storage.service";
import { BookshelfService } from "../bookshelf/bookshelf.service";
import { WishlistService } from "../wishlist/wishlist.service";
import { ReadingProgressService } from "../reading-progress/reading-progress.service";
import { ReadingProgressSyncService } from "../reading-progress/reading-progress-sync.service";
import { SystemListsService } from "../library-auto-organization/system-lists.service";
import { TagsService } from "../library-advanced-organization/tags.service";
import { FilteredViewsService } from "../library-advanced-organization/filtered-views.service";
import { DesktopPreferencesService } from "../desktop-preferences/desktop-preferences.service";
import { TabStateService } from "../desktop-preferences/tab-state.service";
import { LayoutPreferencesService } from "../desktop-preferences/layout-preferences.service";
import { DownloadStatus, SystemListType } from "@prisma/users-service-client";
import type { SyncLibraryPayload } from "../library/library-sync.service";
import { UpdateReadingPreferencesDto } from "7-shared/validation/user/update-reading-preferences.dto";
// Note: Proto types will be generated by ts-proto
// For now, using any types - will be replaced after proto compilation
type GetUserByIdRequest = { id: number };
type GetUserByEmailRequest = { email: string };
type CreateUserRequest = { email: string; password: string; username?: string };
type UpdateUserRequest = { id: number; email?: string; username?: string };
type DeleteUserRequest = { id: number };
type GetUserLibraryRequest = { userId: string | number; page?: number; limit?: number };
type AddToLibraryRequest = { userId: string | number; bookId?: number | string; storyId?: string };
type RemoveFromLibraryRequest = { userId: string; storyId: string };
type UpdateLibraryItemRequest = { userId: string; libraryId: string; customTags?: string[]; notes?: string };
type GetLibraryRequest = {
  userId: string;
  bookshelfId?: string;
  tags?: string[];
  systemListType?: string;
  sort?: string;
  page?: number;
  limit?: number;
  search?: string;
};
type SyncLibraryRequest = { userId: string; deviceId: string; items?: SyncLibraryPayload["items"] };
type BookshelfRequest = { userId: string; bookshelfId?: string; name?: string; description?: string };
type ModifyBookshelfItemRequest = { userId: string; bookshelfId: string; libraryId: string };
type ReorderBookshelfRequest = { userId: string; bookshelfId: string; items: Array<{ libraryId: string; displayOrder?: number }> };
type WishlistRequest = { userId: string; storyId: string; priority?: number; notes?: string };
type GetWishlistRequest = { userId: string };
type ReadingProgressRequest = { userId: string; storyId?: string; chapterId?: string; position?: number; progressPercentage?: number; deviceId?: string };
type SyncProgressRequest = { userId: string; deviceId: string; updates?: Array<{ storyId: string; chapterId: string; position: number }> };
type MarkStoryCompletedRequest = { userId: string; storyId: string };
type TagRequest = { userId: string; tagId?: string; name?: string; color?: string; icon?: string; parentTagId?: string | null };
type ApplyTagRequest = { userId: string; libraryId: string; tagId: string };
type FilteredViewRequest = { userId: string; viewId?: string; name?: string; description?: string; query?: Record<string, unknown>; isAutoUpdating?: boolean };
type ExecuteFilterRequest = { userId: string; query: Record<string, unknown> };
type GetSystemListsRequest = { userId: string };
type UpdateSystemListRequest = { userId: string; listType: string; libraryIds: string[] };
type DownloadStoryRequest = { userId: string; storyId: string; includePremium?: boolean };
type BatchDownloadRequest = { userId: string; storyIds: string[]; includePremium?: boolean };
type GetDownloadQueueRequest = { userId: string; status?: string; storyId?: string };
type SyncBookmarksRequest = { userId: string; deviceId: string; data: any[]; conflictStrategy?: string };
type SyncAnnotationsRequest = { userId: string; deviceId: string; data: any[]; conflictStrategy?: string };
type SyncQueueRequest = { userId: string; deviceId: string };
type ProcessSyncQueueRequest = { userId: string; deviceId: string; operations: Array<{ operationType: string; entity: string; payloadJson: string }> };
type DesktopTabStateRequest = { userId: string; tabs: Record<string, unknown>[]; activeTabId?: string; groups?: Record<string, unknown>[] };
type LayoutPreferencesRequest = { userId: string; layoutPreferences: Record<string, unknown> };
type FocusModeRequest = { userId: string; focusModeSettings?: Record<string, unknown> };
type KeyboardShortcutsRequest = { userId: string; shortcuts?: Record<string, unknown>[] };
type GetReadingPreferencesRequest = { userId: string };
type UpdateReadingPreferencesRequest = UpdateReadingPreferencesDto & { userId: string };
type GetBookmarksRequest = { userId: string; storyId?: string };
type CreateBookmarkRequest = { userId: string; storyId: string; chapterId: string; position: number; note?: string };
type DeleteBookmarkRequest = { bookmarkId: string };
type GetAnnotationsRequest = { userId: string; chapterId?: string; storyId?: string; sourceType?: string };
type CreateAnnotationRequest = { userId: string; storyId?: string; chapterId?: string; selectedText: string; startOffset: number; endOffset: number; note: string; color?: string };
type UpdateAnnotationRequest = { annotationId: string; note?: string; color?: string };
type DeleteAnnotationRequest = { annotationId: string };
type GenerateAnnotationSummaryRequest = { userId: string; annotationIds?: string[]; highlights?: string[]; context?: string };
type ExportAnnotationsRequest = { userId: string; annotationIds?: string[]; sourceType?: string; format: string; targetId?: string };
type UnifyAnnotationsRequest = { userId: string; sourceType: string; sourceId: string; annotations: Array<{ selectedText: string; note?: string }>; sourceUrl?: string };
type GetRevisitationQueueRequest = { userId: string; limit?: number };

@Controller()
export class UsersController {
  constructor(
    private readonly usersService: UsersService,
    private readonly libraryService: LibraryService,
    private readonly librarySyncService: LibrarySyncService,
    private readonly libraryDownloadService: LibraryDownloadService,
    private readonly libraryStorageService: LibraryStorageService,
    private readonly readingPreferencesService: ReadingPreferencesService,
    private readonly bookmarksService: BookmarksService,
    private readonly bookmarkSyncService: BookmarkSyncService,
    private readonly annotationsService: AnnotationsService,
    private readonly annotationExportService: AnnotationExportService,
    private readonly annotationUnificationService: AnnotationUnificationService,
    private readonly annotationRevisitationService: AnnotationRevisitationService,
    private readonly annotationAiSummaryService: AnnotationAiSummaryService,
    private readonly annotationSyncService: AnnotationSyncService,
    private readonly bookshelvesService: BookshelfService,
    private readonly wishlistService: WishlistService,
    private readonly readingProgressService: ReadingProgressService,
    private readonly readingProgressSyncService: ReadingProgressSyncService,
    private readonly tagsService: TagsService,
    private readonly filteredViewsService: FilteredViewsService,
    private readonly systemListsService: SystemListsService,
    private readonly desktopPreferencesService: DesktopPreferencesService,
    private readonly tabStateService: TabStateService,
    private readonly layoutPreferencesService: LayoutPreferencesService
  ) {}

  @GrpcMethod("UsersService", "GetUserById")
  async getUserById(data: GetUserByIdRequest) {
    return this.usersService.getUserById(data.id);
  }

  @GrpcMethod("UsersService", "GetUserByEmail")
  async getUserByEmail(data: GetUserByEmailRequest) {
    return this.usersService.getUserByEmail(data.email);
  }

  @GrpcMethod("UsersService", "CreateUser")
  async createUser(data: CreateUserRequest) {
    return this.usersService.createUser(data);
  }

  @GrpcMethod("UsersService", "UpdateUser")
  async updateUser(data: UpdateUserRequest) {
    return this.usersService.updateUser(data);
  }

  @GrpcMethod("UsersService", "DeleteUser")
  async deleteUser(data: DeleteUserRequest) {
    return this.usersService.deleteUser(data.id);
  }

  @GrpcMethod("UsersService", "GetUserLibrary")
  async getUserLibrary(data: GetUserLibraryRequest) {
    return this.libraryService.getLibrary({
      userId: String(data.userId),
      page: data.page,
      limit: data.limit,
    });
  }

  @GrpcMethod("UsersService", "AddToLibrary")
  async addToLibrary(data: AddToLibraryRequest) {
    const storyId = data.storyId ?? data.bookId;
    return this.libraryService.addToLibrary(String(data.userId), storyId ?? "");
  }

  @GrpcMethod("UsersService", "RemoveFromLibrary")
  async removeFromLibrary(data: RemoveFromLibraryRequest) {
    return this.libraryService.removeFromLibrary(data.userId, data.storyId);
  }

  @GrpcMethod("UsersService", "GetLibrary")
  async getLibrary(data: GetLibraryRequest) {
    return this.libraryService.getLibrary({
      userId: data.userId,
      bookshelfId: data.bookshelfId,
      tagIds: data.tags,
      systemListType: data.systemListType,
      sort: data.sort,
      page: data.page,
      limit: data.limit,
      search: data.search,
    });
  }

  @GrpcMethod("UsersService", "UpdateLibraryItem")
  async updateLibraryItem(data: UpdateLibraryItemRequest) {
    return this.libraryService.updateLibraryItem({
      userId: data.userId,
      libraryItemId: data.libraryId,
      notes: data.notes,
      customTags: data.customTags,
    });
  }

  @GrpcMethod("UsersService", "SyncLibrary")
  async syncLibrary(data: SyncLibraryRequest) {
    // SyncLibraryRequest only has userId and deviceId per proto
    // Server is source of truth - return all library items
    return this.librarySyncService.syncLibrary({
      userId: data.userId,
      deviceId: data.deviceId,
      // items field not in proto - client should use ProcessSyncQueue to push changes
    });
  }

  // Bookshelves
  @GrpcMethod("UsersService", "GetBookshelves")
  async getBookshelves(data: BookshelfRequest) {
    return this.bookshelvesService.getBookshelves(data.userId);
  }

  @GrpcMethod("UsersService", "CreateBookshelf")
  async createBookshelf(data: BookshelfRequest) {
    return this.bookshelvesService.createBookshelf({
      userId: data.userId,
      name: data.name ?? "",
      description: data.description,
    });
  }

  @GrpcMethod("UsersService", "UpdateBookshelf")
  async updateBookshelf(data: BookshelfRequest) {
    return this.bookshelvesService.updateBookshelf({
      userId: data.userId,
      bookshelfId: data.bookshelfId ?? "",
      name: data.name,
      description: data.description,
    });
  }

  @GrpcMethod("UsersService", "DeleteBookshelf")
  async deleteBookshelf(data: BookshelfRequest) {
    return this.bookshelvesService.deleteBookshelf(data.userId, data.bookshelfId ?? "");
  }

  @GrpcMethod("UsersService", "AddToBookshelf")
  async addToBookshelf(data: ModifyBookshelfItemRequest) {
    return this.bookshelvesService.addToBookshelf({
      userId: data.userId,
      bookshelfId: data.bookshelfId,
      libraryItemId: data.libraryId,
    });
  }

  @GrpcMethod("UsersService", "RemoveFromBookshelf")
  async removeFromBookshelf(data: ModifyBookshelfItemRequest) {
    return this.bookshelvesService.removeFromBookshelf({
      userId: data.userId,
      bookshelfId: data.bookshelfId,
      libraryItemId: data.libraryId,
    });
  }

  @GrpcMethod("UsersService", "ReorderBookshelf")
  async reorderBookshelf(data: ReorderBookshelfRequest) {
    const order = [...(data.items ?? [])].sort((a, b) => (a.displayOrder ?? 0) - (b.displayOrder ?? 0)).map((item) => item.libraryId);
    return this.bookshelvesService.reorderBookshelf({
      userId: data.userId,
      bookshelfId: data.bookshelfId,
      order,
    });
  }

  // Wishlist
  @GrpcMethod("UsersService", "GetWishlist")
  async getWishlist(data: GetWishlistRequest) {
    return this.wishlistService.getWishlist(data.userId);
  }

  @GrpcMethod("UsersService", "AddToWishlist")
  async addToWishlist(data: WishlistRequest) {
    return this.wishlistService.addToWishlist({
      userId: data.userId,
      storyId: data.storyId,
      priority: data.priority,
      notes: data.notes,
    });
  }

  @GrpcMethod("UsersService", "RemoveFromWishlist")
  async removeFromWishlist(data: WishlistRequest) {
    return this.wishlistService.removeFromWishlist(data.userId, data.storyId);
  }

  @GrpcMethod("UsersService", "MoveToLibrary")
  async moveToLibraryFromWishlist(data: WishlistRequest) {
    return this.wishlistService.moveToLibrary(data.userId, data.storyId);
  }

  // Reading Preferences
  @GrpcMethod("UsersService", "GetReadingPreferences")
  async getReadingPreferences(data: GetReadingPreferencesRequest) {
    return this.readingPreferencesService.getPreferences(data.userId);
  }

  @GrpcMethod("UsersService", "UpdateReadingPreferences")
  async updateReadingPreferences(data: UpdateReadingPreferencesRequest) {
    const { userId, ...preferences } = data;
    return this.readingPreferencesService.updatePreferences(userId, preferences);
  }

  // Bookmarks
  @GrpcMethod("UsersService", "GetBookmarks")
  async getBookmarks(data: GetBookmarksRequest) {
    return this.bookmarksService.getBookmarks(data.userId, data.storyId);
  }

  @GrpcMethod("UsersService", "CreateBookmark")
  async createBookmark(data: CreateBookmarkRequest) {
    return this.bookmarksService.createBookmark(data.userId, data.storyId, data.chapterId, data.position, data.note);
  }

  @GrpcMethod("UsersService", "DeleteBookmark")
  async deleteBookmark(data: DeleteBookmarkRequest) {
    return this.bookmarksService.deleteBookmark(data.bookmarkId);
  }

  @GrpcMethod("UsersService", "SyncBookmarks")
  async syncBookmarks(data: SyncBookmarksRequest) {
    if (data.conflictStrategy && data.conflictStrategy !== "last-write-wins") {
      return this.bookmarkSyncService.syncWithConflictResolution(data.userId, data.deviceId, data.data, data.conflictStrategy as any);
    }
    return this.bookmarkSyncService.syncBookmarks(data.userId, data.deviceId, data.data);
  }

  // Annotations
  @GrpcMethod("UsersService", "GetAnnotations")
  async getAnnotations(data: GetAnnotationsRequest) {
    return this.annotationsService.getAnnotations(data.userId, {
      chapterId: data.chapterId,
      storyId: data.storyId,
      sourceType: data.sourceType,
    });
  }

  @GrpcMethod("UsersService", "CreateAnnotation")
  async createAnnotation(data: CreateAnnotationRequest) {
    return this.annotationsService.createAnnotation(data.userId, data.storyId, data.chapterId, data.selectedText, data.startOffset, data.endOffset, data.note, data.color);
  }

  @GrpcMethod("UsersService", "UpdateAnnotation")
  async updateAnnotation(data: UpdateAnnotationRequest) {
    return this.annotationsService.updateAnnotation(data.annotationId, data.note, data.color);
  }

  @GrpcMethod("UsersService", "DeleteAnnotation")
  async deleteAnnotation(data: DeleteAnnotationRequest) {
    return this.annotationsService.deleteAnnotation(data.annotationId);
  }

  @GrpcMethod("UsersService", "GenerateAnnotationSummary")
  async generateAnnotationSummary(data: GenerateAnnotationSummaryRequest) {
    const highlights = data.highlights ?? [];
    return this.annotationAiSummaryService.generateSummaryFromAnnotations(highlights);
  }

  @GrpcMethod("UsersService", "ExportAnnotations")
  async exportAnnotations(data: ExportAnnotationsRequest) {
    return this.annotationExportService.exportToMarkdown(data.userId, data.annotationIds);
  }

  @GrpcMethod("UsersService", "UnifyAnnotations")
  async unifyAnnotations(data: UnifyAnnotationsRequest) {
    return this.annotationUnificationService.unifyFromSource(data.userId, data.sourceType, data.annotations);
  }

  @GrpcMethod("UsersService", "GetRevisitationQueue")
  async getRevisitationQueue(data: GetRevisitationQueueRequest) {
    return this.annotationRevisitationService.getRevisitationQueue(data.userId, data.limit);
  }

  @GrpcMethod("UsersService", "SyncAnnotations")
  async syncAnnotations(data: SyncAnnotationsRequest) {
    if (data.conflictStrategy && data.conflictStrategy !== "last-write-wins") {
      return this.annotationSyncService.syncWithConflictResolution(data.userId, data.deviceId, data.data, data.conflictStrategy as any);
    }
    return this.annotationSyncService.syncAnnotations(data.userId, data.deviceId, data.data);
  }

  // Reading Progress
  @GrpcMethod("UsersService", "GetReadingProgress")
  async getReadingProgress(data: ReadingProgressRequest) {
    return this.readingProgressService.getReadingProgress(data.userId, data.storyId);
  }

  @GrpcMethod("UsersService", "UpdateReadingProgress")
  async updateReadingProgress(data: ReadingProgressRequest) {
    return this.readingProgressService.updateReadingProgress({
      userId: data.userId,
      storyId: data.storyId ?? "",
      chapterId: data.chapterId ?? "",
      position: data.position,
      progress: data.progressPercentage,
      deviceId: data.deviceId,
    });
  }

  @GrpcMethod("UsersService", "SyncReadingProgress")
  async syncReadingProgress(data: SyncProgressRequest) {
    return this.readingProgressSyncService.syncProgress(data.userId, data.deviceId, data.updates);
  }

  @GrpcMethod("UsersService", "MarkStoryCompleted")
  async markStoryCompleted(data: MarkStoryCompletedRequest) {
    return this.readingProgressService.markAsCompleted(data.userId, data.storyId);
  }

  // Tags & Filtered Views
  @GrpcMethod("UsersService", "CreateTag")
  async createTag(data: TagRequest) {
    return this.tagsService.createTag({
      userId: data.userId,
      name: data.name ?? "",
      color: data.color,
      icon: data.icon,
      parentTagId: data.parentTagId ?? undefined,
    });
  }

  @GrpcMethod("UsersService", "UpdateTag")
  async updateTag(data: TagRequest) {
    return this.tagsService.updateTag({
      userId: data.userId,
      tagId: data.tagId ?? "",
      name: data.name,
      color: data.color,
      icon: data.icon,
      parentTagId: data.parentTagId,
    });
  }

  @GrpcMethod("UsersService", "DeleteTag")
  async deleteTag(data: TagRequest) {
    return this.tagsService.deleteTag(data.userId, data.tagId ?? "");
  }

  @GrpcMethod("UsersService", "GetTags")
  async getTags(data: TagRequest) {
    return this.tagsService.getAllTags(data.userId);
  }

  @GrpcMethod("UsersService", "ApplyTagToLibrary")
  async applyTagToLibrary(data: ApplyTagRequest) {
    return this.tagsService.applyTagToLibrary(data.userId, data.tagId, data.libraryId);
  }

  @GrpcMethod("UsersService", "RemoveTagFromLibrary")
  async removeTagFromLibrary(data: ApplyTagRequest) {
    return this.tagsService.removeTagFromLibrary(data.tagId, data.libraryId);
  }

  @GrpcMethod("UsersService", "CreateFilteredView")
  async createFilteredView(data: FilteredViewRequest) {
    return this.filteredViewsService.createFilteredView({
      userId: data.userId,
      name: data.name ?? "",
      description: data.description,
      query: data.query ?? {},
      isAutoUpdating: data.isAutoUpdating,
    });
  }

  @GrpcMethod("UsersService", "UpdateFilteredView")
  async updateFilteredView(data: FilteredViewRequest) {
    return this.filteredViewsService.updateFilteredView({
      userId: data.userId,
      viewId: data.viewId ?? "",
      name: data.name,
      description: data.description,
      query: data.query,
      isAutoUpdating: data.isAutoUpdating,
    });
  }

  @GrpcMethod("UsersService", "DeleteFilteredView")
  async deleteFilteredView(data: FilteredViewRequest) {
    return this.filteredViewsService.deleteFilteredView(data.userId, data.viewId ?? "");
  }

  @GrpcMethod("UsersService", "GetFilteredViews")
  async getFilteredViews(data: FilteredViewRequest) {
    return this.filteredViewsService.getFilteredViews(data.userId);
  }

  @GrpcMethod("UsersService", "ExecuteFilter")
  async executeFilter(data: ExecuteFilterRequest) {
    return this.filteredViewsService.executeFilter(data.userId, data.query);
  }

  // System Lists
  @GrpcMethod("UsersService", "GetSystemLists")
  async getSystemLists(data: GetSystemListsRequest) {
    return this.systemListsService.getSystemLists(data.userId);
  }

  @GrpcMethod("UsersService", "UpdateSystemList")
  async updateSystemList(data: UpdateSystemListRequest) {
    return this.systemListsService.updateSystemList({
      userId: data.userId,
      listType: data.listType as SystemListType,
      libraryItemIds: data.libraryIds,
    });
  }

  // Download Management
  @GrpcMethod("UsersService", "DownloadStory")
  async downloadStory(data: DownloadStoryRequest) {
    return this.libraryDownloadService.downloadStory(data.userId, data.storyId, data.includePremium);
  }

  @GrpcMethod("UsersService", "BatchDownload")
  async batchDownload(data: BatchDownloadRequest) {
    return this.libraryDownloadService.batchDownload(data.userId, data.storyIds, data.includePremium);
  }

  @GrpcMethod("UsersService", "GetDownloadQueue")
  async getDownloadQueue(data: GetDownloadQueueRequest) {
    const statusKey = data.status ? (data.status.toUpperCase() as keyof typeof DownloadStatus) : undefined;
    const resolvedStatus = statusKey ? DownloadStatus[statusKey] : undefined;
    return this.libraryDownloadService.getDownloadQueue(data.userId, {
      status: resolvedStatus,
      storyId: data.storyId,
    });
  }

  @GrpcMethod("UsersService", "GetStorageUsage")
  async getStorageUsage(data: { userId: string }) {
    return this.libraryStorageService.getStorageUsage(data.userId);
  }

  // Sync Queue Utilities
  @GrpcMethod("UsersService", "GetPendingSyncQueue")
  async getPendingSyncQueue(data: SyncQueueRequest) {
    return this.librarySyncService.getPendingSyncQueue(data.userId, data.deviceId);
  }

  @GrpcMethod("UsersService", "ProcessSyncQueue")
  async processSyncQueue(data: ProcessSyncQueueRequest) {
    return this.librarySyncService.processSyncQueue(data.userId, data.operations);
  }

  // Desktop Preferences
  @GrpcMethod("UsersService", "UpdateTabState")
  async updateTabState(data: DesktopTabStateRequest) {
    await this.tabStateService.updateTabState(data.userId, {
      tabs: data.tabs,
      activeTabId: data.activeTabId,
      groups: data.groups,
    });
    return this.desktopPreferencesService.getDesktopPreferences(data.userId);
  }

  @GrpcMethod("UsersService", "UpdateLayoutPreferences")
  async updateLayoutPreferences(data: LayoutPreferencesRequest) {
    await this.layoutPreferencesService.updateLayoutPreferences(data.userId, data.layoutPreferences);
    return this.desktopPreferencesService.getDesktopPreferences(data.userId);
  }

  @GrpcMethod("UsersService", "UpdateFocusMode")
  async updateFocusMode(data: FocusModeRequest) {
    return this.desktopPreferencesService.updateFocusMode(data.userId, data.focusModeSettings ?? {});
  }

  @GrpcMethod("UsersService", "UpdateKeyboardShortcuts")
  async updateKeyboardShortcuts(data: KeyboardShortcutsRequest) {
    return this.desktopPreferencesService.updateKeyboardShortcuts(data.userId, data.shortcuts ?? []);
  }
}

